[ID-11] 에디터페이지 디자인 1차 수정
FluffySnowTeam/IDEARLY-FE pull request #18
Opened 2023-12-17 18:34 UTC by stop0ho

## 이슈 번호
ID-11
- 📌

## 작업 분류

- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 프로젝트 구조 변경
- [X] 기타

## 작업 상세 내용
- 1번 문제 먼저 뜨게 (id로 첫 번째 문제 활성화 되어있도록)
- 언어 선택 default 언어 python으로 되어있도록
- 음소거 버튼 없애기

## 다음 할 일
- 에디터 연결
- 초기화 기능 구현
- 언어 선택 기능 구현
- 실행 눌렀을 때 컴파일 된 정보 나오도록 구현
## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**
1번 문제 먼저 뜨도록 구현하기는 했는데, 현재 목업 데이터로 연결 되어 있어서 1번 id를
```javascript
path.search = `?id=${fakeProblem[0].id}`;
const [selectedProblemId, setSelectedProblemId] = useState<string | null>(
    fakeProblem[0].id
);
```
와 같이 `fakeProblem[0].id`로 구현하였습니다. 이 부분은 추후에 수정하면 될까요? 아니면 더 좋은 방법이 있을까요?  

🔴 **이건 반드시 확인해 주세요!**

2023-12-18 01:25 UTC, dbswl701 commented
지호님! node_modules 폴더가 올라가있습니다!

2023-12-18 01:33 UTC, zivivle reviewed
수정후 다시 pr 부탁드려요!

2023-12-18 04:14 UTC, zivivle commented on idearly/src/pages/AlgorithmSolvingPage/AlgorithmSolvingPage.tsx
> +} from './components';
vscode 프리티어 설정이 안되고 있는 것 같아요! 한 번만 확인해 주세요!

2023-12-18 04:15 UTC, zivivle commented on idearly/src/pages/AlgorithmSolvingPage/components/AlgorithmNav/AlgorithmNav.tsx
> +    fakeProblem[0].id
이부분은 나중에 api 연동할때 받아온 데이터중에 1번 문제를 기본값으로 설정하도록 해야겠네요 지금은 수정할 수 없는 부분으로 보입니다.

2023-12-18 05:43 UTC, dbswl701 requested changes
성경님이 말씀하신 프리티어 부분이랑, node_modules와 같이 프로젝트 폴더 바깥에 있던 package.json 등등의 파일 정리가 필요할 것 같아요!

2023-12-19 01:18 UTC, dbswl701 approved these changes

2023-12-19 01:29 UTC, zivivle approved these changes
수고하셨습니다!

2023-12-19 03:32 UTC, merged